spring.application.name: sia-task-config

server.port: 10615

spring.application.cnname: 任务编排中心
#management.security.enabled: false
#endpoints.health.sensitive: false

#zooKeeperHosts: 127.0.0.1:12181
zooKeeperHosts: 127.0.0.1:2181

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/siatask?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

#############################################################
############## mybatis config ###############################
#############################################################
# mybatis配置
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.sia.core.entity
#
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

#############################################################
############## log config ###################################
#############################################################
logging.file: ./logs/${spring.application.name}.log

# task根路径
# 可选参数，需要overwritten此参数时，打开注释并填写指定的ZK根路径，否则默认为SkyWorldOnlineTask
#ZK_ONLINE_ROOT_PATH: SkyWorldOnlineTask

# 用户权限  所有权限（创建、读取、写入，删除，赋权）
# 可选参数，需要overwritten此参数时，打开注释并填写指定的所有用户权限，否则默认为 SIA:SkyWorld
# ALLAUTH: SIA:SkyWorld

# 用户权限  只有创建权限
# 可选参数，需要overwritten此参数时，打开注释并填写指定的创建权限，否则默认为 guest:guest
# CREATEAUTH: guest:guest

# 用户权限  ZK权限模式
# 可选参数，需要overwritten此参数时，打开注释并填写指定的ZK权限模式，否则默认为 digest
# DIGEST: digest