spring.application.name: sia-task-admin
spring.application.cnname: 任务编排中心
server.port: 10615

#-------------------------------------------------
#zookeeper config
sia:
  task:
    zookeeper:
      host-list: 127.0.0.1:2181
      root-path: SIA-ROOT
      sleep-ms-between-retries: 5000
      connect-lost-retry-times: 10
      max-wait-seconds: 60
      root-auth: SIA:ROOT
      create-auth: guest:guest
      digest-auth: digest

#-------------------------------------------------
#datasource config
spring:
  datasource:
    name: prod
    url: jdbc:mysql://127.0.0.1:3503/skyworld_task?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: xxxxxx
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
#-------------------------------------------------
#mybatis config
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.sia.base.core.entity
  configuration.default-statement-timeout: 60
#
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

#-------------------------------------------------
# log config
logging.file: ./logs/${spring.application.name}.log

