spring.application.name: sia-task-scheduler
spring.application.cnname: 任务调度中心
#应用端口号
server.port: 19011

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#sia-task config
# task根路径
# 可选参数，需要overwritten此参数时，打开注释并填写指定的ZK根路径，否则默认为SIA-ROOT
#sia.task.zookeeper.root-path: SIA-ROOT

# 用户权限  所有权限（创建、读取、写入，删除，赋权）
# 可选参数，需要overwritten此参数时，打开注释并填写指定的所有用户权限，否则默认为 SIA:ROOT
#sia.task.zookeeper.root-auth: SIA:ROOT

# 用户权限  只有创建权限
# 可选参数，需要overwritten此参数时，打开注释并填写指定的创建权限，否则默认为 guest:guest
#sia.task.zookeeper.create-auth: guest:guest

# 用户权限  ZK权限模式
# 可选参数，需要overwritten此参数时，打开注释并填写指定的ZK权限模式，否则默认为 digest
#sia.task.zookeeper.auth-schema: digest
sia:
  task:
    alarm-threshold: 200
    fault-tolerant: 1
    log:
      collector:
        enabled: true
    alarm:
      email:
        service-id: http://EMAIL-ALARM-SERVICE_ID/v1/sendEmail
        elapse: 7200000
        subject: 微服务任务调度平台预警
        default-email: you email address
    zookeeper:
      host-list: 127.0.0.1:2181
      root-path: SIA-ROOT
      sleep-ms-between-retries: 5000
      connect-lost-retry-times: 10
      max-wait-seconds: 60
      root-auth: SIA:ROOT
      create-auth: guest:guest
      auth-schema: digest
    metadata:
      sync:
        store: false
        delay: 60000

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
eureka.client.serviceUrl.defaultZone: http://127.0.0.1:61352/eureka/
# 注册时使用ip而不是主机名
eureka.instance.preferIpAddress: true
# ${spring.cloud.client.ipAddress} 为IP地址
eureka.instance.instance-id: ${spring.cloud.client.ipAddress}:${server.port}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/sia_task?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.sia.core.entity

# 预警邮件配置
SKYTRAIN_DEFAULT_EMAIL:
#邮件服务地址：127.0.0.1:12026
EMAIL_SERVICE_REQUESTPATH: http://127.0.0.1:12026/v1/sendEmail

# 调度器执行的JOB个数阈值，超过则通知添加资源
onlinetask.job.alarm.threshold: 100
# 负载均衡的级别
onlinetask.job.fault.tolerant: 1

#############################################################
############## log config ###################################
#############################################################
logging.file: ./logs/${spring.application.name}.log
