spring.application.name: sia-task-scheduler
spring.application.cnname: 任务调度中心
#应用端口号
server.port: 19011
#配置报警邮箱，当该服务出现问题后会触发报警(建议配置成组邮箱)，如下：
eureka.instance.metadataMap.alarmEmail: your-team.list@creditease.cn

#开启全信息展示，默认值为true，不展示所有信息
#endpoints.health.sensitive: false
#management.security.enabled: false

#注册中心地址
eureka.client.serviceUrl.defaultZone: http://your-eureka-host:eureka-port/eureka/

# 注册时使用ip而不是主机名
eureka.instance.preferIpAddress: true
# ${spring.cloud.client.ipAddress} 为IP地址
eureka.instance.instance-id: ${spring.cloud.client.ipAddress}:${server.port}

#############################################################
############## zooKeeperHosts config ########################
#############################################################
zooKeeperHosts: 127.0.0.1:2181

# 使用的MYSQL地址
spring:
    datasource:
        name: test
        url: jdbc:mysql://your-mysql-address:3306/skyworld_task?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.sia.core.entity
  configuration.default-statement-timeout: 60

# 预警邮件配置 选配
SKYTRAIN_DEFAULT_EMAIL:
EMAIL_SERVICE_REQUESTPATH: http://xxx-EMAIL-ALARM/v1/sendEmail

# 调度器执行的JOB个数阈值，超过则通知添加资源
sia.job.alarm.threshold: 100
# 负载均衡的级别
sia.job.fault.tolerant: 1

#############################################################
############## log config ###################################
#############################################################
logging.file: ./logs/${spring.application.name}.log


# task根路径
# 可选参数，需要overwritten此参数时，打开注释并填写指定的ZK根路径，否则默认为SkyWorldOnlineTask
# ZK_ONLINE_ROOT_PATH: SkyWorldOnlineTask
