spring.application.name: sia-task-scheduler
spring.application.cnname: 任务调度中心
#应用端口号
server.port: 19011

#开启全信息展示，默认值为true，不展示所有信息
#endpoints.health.sensitive: false
#management.security.enabled: false

# 使用的ZK地址
#127.0.0.1:2181
#############################################################
############## zooKeeperHosts config ########################
#############################################################
#zooKeeperSessionTime: 2000
zooKeeperHosts: 127.0.0.1:2181

# 使用的MYSQL地址
#jdbc:mysql://127.0.0.1:3306/skyworld_scheduler?useUnicode=true&characterEncoding=utf8
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/skyworld_task?useUnicode=true&characterEncoding=utf8
        username: root
        password: ****
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.sia.core.entity

# 预警邮件配置
SKYTRAIN_DEFAULT_EMAIL:
# 邮件服务地址：127.0.0.1:12026
EMAIL_SERVICE_REQUESTPATH: http://127.0.0.1:12026/v1/sendEmail

# 调度器执行的JOB个数阈值，超过则通知添加资源
onlinetask.job.alarm.threshold: 100
# 负载均衡的级别
onlinetask.job.fault.tolerant: 1

#############################################################
############## log config ###################################
#############################################################
logging.file: ./logs/${spring.application.name}.log

# task根路径
# 可选参数，需要overwritten此参数时，打开注释并填写指定的ZK根路径，否则默认为SkyWorldOnlineTask
#ZK_ONLINE_ROOT_PATH: SkyWorldOnlineTask

# 用户权限  所有权限（创建、读取、写入，删除，赋权）
# 可选参数，需要overwritten此参数时，打开注释并填写指定的所有用户权限，否则默认为 SIA:SkyWorld
# ALLAUTH: SIA:SkyWorld

# 用户权限  只有创建权限
# 可选参数，需要overwritten此参数时，打开注释并填写指定的创建权限，否则默认为 guest:guest
# CREATEAUTH: guest:guest

# 用户权限  ZK权限模式
# 可选参数，需要overwritten此参数时，打开注释并填写指定的ZK权限模式，否则默认为 digest
# DIGEST: digest